name: Pull Request

on: pull_request

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - run: curl --output detekt-cli.jar -sSLO https://github.com/detekt/detekt/releases/download/v1.16.0/detekt-cli-1.16.0-all.jar
      - run: curl --output detekt-formatting.jar -sSLO https://github.com/detekt/detekt/releases/download/v1.16.0/detekt-formatting-1.16.0.jar
      - run: java -jar detekt-cli.jar --report xml:detekt-report.xml --plugins detekt-formatting.jar
      - name: Run Danger
        uses: docker://ghcr.io/danger/danger-kotlin:1.0.0-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - name: Build app
        run: ./gradlew assembleDebug
      - name: Run tests
        run: ./gradlew testDebugUnitTest
